### ISSUE TITLE
Trajectory plot

### ISSUE THREAD

**Issue by Resonanz** [soft-matter/trackpy#342]
A difference between 0.2.4 and 0.3.0 is that in the latter a legend is placed over and obstructs a section of the trajectory plot. This is shown in Daniel's walkthru example also.  I'm not sure that the legend is necessary and certainly detracts from the plot.  Can it be removed or switched off?

**Comment by caspervdw** [comment]
Thanks for the report! I can't see the use of the legend too, it should be disabled by default.

**Comment by danielballan** [comment]
@tacaswell Any idea whether this changed upstream? I don't recall touching the legend stuff in our code.

**Comment by tacaswell** [comment]
It looks like if you pass a `legend=False` kwarg it will disable the legend.

Looking at https://github.com/soft-matter/trackpy/blob/master/trackpy/plots.py#L56 I do not see what has changed sense 2013, but there is clearly a call to `plt.legend` (not `ax.legend`).  I do not think any upstream changes should have affected this.

**Comment by caspervdw** [comment]
I think there is a simple bug in our code: when `legend` kwarg is not given, it will default to `None` in the `make_axes` wrapper. The legend is then shown when there `legend` is not `False`. This should have been `legend not in [False, None]` or something like that. Effectively, legends are shown by default now.

Probably automatic labeling of the plots (something between pandas and matlotlib) has been fixed either in matplotlib or pandas, which is good. I think the default behaviour for us should have been to only show a legend when `legend==True`. I will push a PR with that fix soon.

**Comment by caspervdw** [comment]
Closing through https://github.com/soft-matter/trackpy/pull/357

**Comment by Resonanz** [comment]
It appears that this is still broken... using the walkthrough cold, a VERY long legend is generated when making a trajectory plot and drift plot.

**Comment by danielballan** [comment]
Are you using the latest version of trackpy? I *just* uploaded the conda packages for v0.3.1.

**Comment by Resonanz** [comment]
LOL, using 0.3.0, installed fresh a few days ago. Will grab the latest now and try.

**Comment by Resonanz** [comment]
Ouch, the conda update failed... are you using Python 3.5?

**Comment by danielballan** [comment]
What do you mean by failed? We distribute packages for 2.7, 3.3, 3.4, and
3.5.

**Comment by Resonanz** [comment]
Here is the error...

(C:\Users\resonanz\AppData\Local\Continuum\Anaconda3) C:\Users\resonanz\ParticleTrac
king>conda update -c soft-matter trackpy
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment C:\Users\resonanz\AppData\Local\Conti
nuum\Anaconda3:

The following packages will be UPDATED:

    trackpy: 0.3.0-py35_2 soft-matter --> 0.3.1-py35_0 soft-matter

Proceed ([y]/n)? y

Extracting packages ...
An unexpected error has occurred, please consider sending the            |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\resonanz\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.p
y", line 5, in <module>
    sys.exit(main())
  File "C:\Users\resonanz\AppData\Local\Continuum\Anaconda3\lib\site-packages\cond
a\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Users\resonanz\AppData\Local\Continuum\Anaconda3\lib\site-packages\cond
a\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Users\resonanz\AppData\Local\Continuum\Anaconda3\lib\site-packages\cond
a\cli\main_update.py", line 64, in execute
    install(args, parser, 'update')
  File "C:\Users\resonanz\AppData\Local\Continuum\Anaconda3\lib\site-packages\cond
a\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\resonanz\AppData\Local\Continuum\Anaconda3\lib\site-packages\cond
a\plan.py", line 599, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\resonanz\AppData\Local\Continuum\Anaconda3\lib\site-packages\cond
a\instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "C:\Users\resonanz\AppData\Local\Continuum\Anaconda3\lib\site-packages\cond
a\instructions.py", line 59, in EXTRACT_CMD
    extract(arg)
  File "C:\Users\resonanz\AppData\Local\Continuum\Anaconda3\lib\site-packages\cond
a\install.py", line 857, in extract
    t.extractall(path=temp_path)
  File "C:\Users\resonanz\AppData\Local\Continuum\Anaconda3\lib\tarfile.py", line
1996, in extractall
    numeric_owner=numeric_owner)
  File "C:\Users\resonanz\AppData\Local\Continuum\Anaconda3\lib\tarfile.py", line
2038, in extract
    numeric_owner=numeric_owner)
  File "C:\Users\resonanz\AppData\Local\Continuum\Anaconda3\lib\tarfile.py", line
2108, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Users\resonanz\AppData\Local\Continuum\Anaconda3\lib\tarfile.py", line
2148, in makefile
    with bltn_open(targetpath, "wb") as target:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\resonanz\\AppData\\Local\\Contin
uum\\Anaconda3\\pkgs\\trackpy-0.3.1-py35_0.tmp\\info\\recipe\\:wq'

(C:\Users\resonanz\AppData\Local\Continuum\Anaconda3) C:\Users\resonanz\ParticleTrac
king>

**Comment by Resonanz** [comment]
I have uninstalled trackpy, pillow and matplotlib and tried to re-install them all... trackpy is the one that won't re-install. Mmmmm.
